- name: Deploy Docker Container
  hosts: web
  become: true

  tasks:

    - name: Stop old container
      shell: docker stop webapp || true

    - name: Remove old container
      shell: docker rm webapp || true

    - name: Remove old image
      shell: docker rmi lohar45/jen_ansi_dev:latest || true

    - name: Pull latest image
      shell: docker pull lohar45/jen_ansi_dev:latest

    - name: Run container
      shell: docker run -d -p 80:80 --name webapp lohar45/jen_ansi_dev:latest
