- name: Deploy container
  hosts: web
  become: yes
  tasks:

    - name: Stop old container
      shell: docker stop ecommerce || true

    - name: Remove old container
      shell: docker rm ecommerce || true

    - name: Remove old image
      shell: docker rmi lohar45/jen_ansi_pro || true

    - name: Pull latest image
      shell: docker pull lohar45/jen_ansi_pro

    - name: Run container
      shell: docker run -d --name ecommerce -p 80:80 lohar45/jen_ansi_pro
